baseURL: https://salmon3g.github.io # ç»‘å®šçš„åŸŸå
languageCode: zh-cn
title: å¾€ä¸œè¡Œ
theme: PaperMod
enableInlineShortcodes: true
enableEmoji: true # å…è®¸ä½¿ç”¨ Emoji è¡¨æƒ…ï¼Œå»ºè®® true
enableRobotsTXT: true # å…è®¸çˆ¬è™«æŠ“å–åˆ°æœç´¢å¼•æ“ï¼Œå»ºè®® true
buildDrafts: false
buildFuture: false
buildExpired: false
googleAnalytics:  # è°·æ­Œç»Ÿè®¡
paginate: 6    # é¦–é¡µæ¯é¡µæ˜¾ç¤ºçš„æ–‡ç« æ•°
summaryLength: 120 # æ–‡ç« æ¦‚è§ˆçš„è‡ªå­—æ•°ï¼Œé»˜è®¤70

minify:
  disableXML: true
  # minifyOutput: true

permalinks: # è®¿é—®åšå®¢æ—¶ç½‘å€çš„æ˜¾ç¤ºå½¢å¼
  post: "/:title/"
  # post: "/:year/:month/:day/:title/"

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: äº§å“
          url: categories/pm/
          weight: 5
        - name: åˆ†æ
          url: categories/analytics/
          weight: 7
        - name: é˜…è¯»
          url: categories/reading/
          weight: 6
        - name: ç”Ÿæ´»
          url: categories/life/
          weight: 10
        - name: å½’ç±»
          url: archives/
          weight: 18
        - name: æ ‡ç­¾
          url: tags/
          weight: 19
        - name: æœç´¢
          url: search/
          weight: 20
        - name: å…³äº
          url: about/
          weight: 21           

outputs:
  home:
    - HTML
    - RSS
    - JSON

# è¿™é‡Œçš„å‚æ•°ä¼šè¢«ä»£ç ä»¥ .Site.Params çš„å½¢å¼è¯»å–
params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "è¥¿æ–¹æœ‰çœŸç»ï¼Œæˆ‘å¾€ä¸œè¡Œ"
  author: wangdongxing
  defaultTheme: auto  # defaultTheme: light or  dark
  disableThemeToggle: false
  DateFormat: "2006-01-02"
  ShowShareButtons: true
  ShowReadingTime: true
  disableSpecialistPost: false
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  hideFooter: false # éšè—é¡µè„š
  ShowWordCounts: true
  ShowLastMod: true #æ˜¾ç¤ºæ–‡ç« æ›´æ–°æ—¶é—´
  ShowAllPagesInArchive: true
  disableSpecial1stPost: false
  ShowToc: true # æ˜¾ç¤ºç›®å½•
  TocOpen: true # è‡ªåŠ¨å±•å¼€ç›®å½•
  comments: false
  autonumbering: true

  profileMode:
      enabled: false
      title: PaperMod
      # imageUrl: "#"
      # imageTitle: my image
      # imageWidth: 120
      # imageHeight: 120
      # buttons:
      #     - name: Archives
      #       url: archives
      #     - name: Tags
      #       url: tags

  homeInfoParams:
      Title: "Hi there ğŸ‘‹"
      Content: 
        <ul><li>Welcome to my blog âœ¨</li>
        <li>I will share my work ğŸ‘¨ğŸ»â€ğŸ’» and life ğŸ– notes here.</li>
        <li></li>
        <li>åšå­¦æ…æ€ï¼Œæ˜è¾¨ç¬ƒè¡Œã€‚</li>
        <li>æ•°æ®è¡Œä¸šä»ä¸š 10 å¹´ï¼Œç›®å‰åœ¨é¹…å‚åšæ•°æ®äº§å“ç»ç†ã€‚æ›´å¤šä»‹ç»è§ï¼š<a href="/about">å…³äº</a></li>
        </ul>
 
  socialIcons:
    - name: email
      url: "mailto:datapig@126.com"
    - name: RSS
      url: "index.xml"

  label: # å·¦ä¸Šè§’å›¾æ ‡
    text: "å¾€ä¸œè¡Œ"
    # icon: "img/favicon.ico"
    iconHeight: 35

  analytics:
    google:
      SiteVerificationTag: ""

  assets:
    favicon: "img/favicon.ico"
    favicon16x16: ""
    favicon32x32: ""
    apple_touch_icon: ""
    safari_pinned_tab: "apple-touch-icon.png"

  cover:
      hidden: true # hide everywhere but not in structured data
      hiddenInList: true # hide on list pages and home
      hiddenInSingle: true # hide on single page

  editPost:
      URL: "https://github.com/<path_to_repo>/content"
      Text: "Edit" # edit text
      appendFilePath: true # to append file path to Edit link

  fuseOpts: # æœç´¢é…ç½®
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: [ "title", "permalink", "summary", "content"]

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true # HUGO é»˜è®¤è½¬ä¹‰ Markdown æ–‡ä»¶ä¸­çš„ HTML ä»£ç ï¼Œå¦‚éœ€å¼€å¯çš„è¯
  highlight:
    style: monokai
    codeFences: true
    guessSyntax: true
    noClasses: true
    tabWidth: 2
    lineNumbersInTable: true #ï¼šä½¿ç”¨è¡¨æ¥æ ¼å¼åŒ–è¡Œå·å’Œä»£ç ,è€Œä¸æ˜¯ æ ‡ç­¾ã€‚è¿™ä¸ªå±æ€§ä¸€èˆ¬è®¾ç½®ä¸º true.
    # codeFences: true
    # hl_Lines: true #é«˜äº®çš„è¡Œå·ï¼Œä¸€èˆ¬è¿™ä¸ªä¸è®¾ç½®ï¼Œå› ä¸ºæ¯ä¸ªä»£ç å—æˆ‘ä»¬å¯èƒ½å¸Œæœ›è®©é«˜äº®çš„åœ°æ–¹ä¸ä¸€æ ·
    # anchorLineNos: true
    # lineNoStart: true #è¡Œå·ä»ç¼–å·å‡ å¼€å§‹ï¼Œä¸€èˆ¬ä» 1 å¼€å§‹ã€‚
    # lineNos: true  # æ˜¯å¦æ˜¾ç¤ºè¡Œå·ï¼Œæˆ‘æ¯”è¾ƒå–œæ¬¢æ˜¾ç¤ºï¼Œæ‰€ä»¥æˆ‘è®¾ç½®çš„ä¸º true.
    # noClasses: true #ï¼šä½¿ç”¨ class æ ‡ç­¾ï¼Œè€Œä¸æ˜¯å†…åµŒçš„å†…è”æ ·å¼

  # twikooè¯„è®º
  # twikoo:
  #   version: 1.5.8 # å¡«å†™twikooç‰ˆæœ¬å·
  #   id:  # å¡«å†™è‡ªå·±çš„twikoo id
  #   region:  # ç¯å¢ƒåœ°åŸŸï¼Œé»˜è®¤ä¸º ap-shanghaiï¼Œå¦‚æœæ‚¨çš„ç¯å¢ƒåœ°åŸŸä¸æ˜¯ä¸Šæµ·ï¼Œéœ€ä¼ æ­¤å‚æ•°ï¼Œè¯·çœ‹twikooå®˜æ–¹æ–‡æ¡£